export const accounts = [
  {
    id: "922650",
    secretname: "ola",
    title: "th 15 almost maxed",
    cover: "/accounts/ola/cover.webp",
    th: "155",
    heroes: {
      king: 80,
      queen: 83,
      warden: 60,
      champion: 31,
    },
    walls: {
      lvl14: 172,
      lvl15: 153,
    },
    monolith: 2,
    eagle: 6,
    scatter: [4, 3],
    inferno: [9, 8, 9],
    spelltower: [3, 3],
    xbow: [10, 10, 10, 10],
    airdefense: [13, 13, 13, 13],
    wizzard: [15, 15, 15, 15, 15],
    tesla: [14, 13, 13, 13, 13],
    archer: [21, 21, 21, 21, 21, 21, 21, 21],
    cannon: [21, 21, 21, 21, 21, 21, 21],
    sweeper: [7, 7],
    bombtower: [10, 10],
    mortar: [15, 15, 15, 15],
    builderhut: [4, 4, 4, 4, 4, 6],
    pethouse: 8,
    workshop: 7,
    spellfactory: 7,
    darkspell: 5,
    barraks: 16,
    darkbarraks: 10,
    armycamps: [12, 12, 12, 12],
    mainimgs: [
      "/accounts/ola/cover.webp",
      "/accounts/ola/bb1.webp",
      "/accounts/ola/bb2.webp",
      "/accounts/ola/mainstatus.webp",
      "/accounts/ola/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/ola/buildersgemsname.webp",
      "/accounts/ola/items.webp",
      "/accounts/ola/medals.webp",
      "/accounts/ola/scene.webp",
    ],
    heroskins: [
      "/accounts/ola/kingskin.webp",
      "/accounts/ola/queenskin.webp",
      "/accounts/ola/wardenskin.webp",
      "/accounts/ola/championskin.webp",
    ],
    price: 235,
  },
  {
    id: "276207",
    secretname: "fo15fo",
    title: "great th 15 scenery & skins",
    cover: "/accounts/fo15fo/cover.webp",
    th: "155",
    heroes: {
      king: 80,
      queen: 82,
      warden: 61,
      champion: 30,
    },
    walls: {
      lvl14: 153,
      lvl15: 172,
    },
    monolith: 2,
    eagle: 6,
    scatter: [4, 3],
    inferno: [9, 9, 9],
    spelltower: [3, 3],
    xbow: [10, 10, 10, 10],
    airdefense: [13, 13, 13, 13],
    wizzard: [14, 14, 14, 14, 14],
    tesla: [13, 13, 13, 13, 13],
    archer: [21, 21, 21, 21, 21, 21, 21, 21],
    cannon: [21, 21, 21, 20, 20, 20, 20],
    sweeper: [7, 7],
    bombtower: [10, 10],
    mortar: [14, 14, 14, 14],
    builderhut: [4, 4, 4, 4, 4, 6],
    pethouse: 8,
    workshop: 7,
    spellfactory: 7,
    darkspell: 5,
    barraks: 16,
    darkbarraks: 10,
    armycamps: [12, 12, 12, 12],
    mainimgs: [
      "/accounts/fo15fo/cover.webp",
      "/accounts/fo15fo/bb1.webp",
      "/accounts/fo15fo/bb2.webp",
      "/accounts/fo15fo/mainstatus.webp",
      "/accounts/fo15fo/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/fo15fo/buildersgemsname.webp",
      "/accounts/fo15fo/items.webp",
      "/accounts/fo15fo/medals.webp",
      "/accounts/fo15fo/scene.webp",
    ],
    heroskins: [
      "/accounts/fo15fo/kingskin.webp",
      "/accounts/fo15fo/queenskin.webp",
      "/accounts/fo15fo/wardenskin.webp",
      "/accounts/fo15fo/championskin.webp",
    ],
    price: 250,
  },
  {
    id: "266837",
    secretname: "fo1415",
    title: "new th 15 scenery & skins",
    cover: "/accounts/fo1415/cover.webp",
    th: "154",
    heroes: {
      king: 80,
      queen: 82,
      warden: 56,
      champion: 30,
    },
    walls: {
      lvl14: 19,
      lvl15: 306,
    },
    monolith: 2,
    eagle: 6,
    scatter: [3, 3],
    inferno: [8, 8, 8],
    spelltower: [1, 1],
    xbow: [9, 9, 9, 9],
    airdefense: [12, 12, 12, 12],
    wizzard: [14, 14, 14, 14, 14],
    tesla: [13, 13, 13, 13, 13],
    archer: [20, 20, 20, 20, 20, 20, 20, 20],
    cannon: [20, 20, 20, 20, 20, 20, 20],
    sweeper: [7, 7],
    bombtower: [9, 9],
    mortar: [14, 14, 14, 14],
    builderhut: [4, 4, 4, 4, 4, 6],
    pethouse: 5,
    workshop: 6,
    spellfactory: 7,
    darkspell: 5,
    barraks: 16,
    darkbarraks: 9,
    armycamps: [12, 12, 12, 12],
    mainimgs: [
      "/accounts/fo1415/cover.webp",
      "/accounts/fo1415/bb1.webp",
      "/accounts/fo1415/bb2.webp",
      "/accounts/fo1415/mainstatus.webp",
      "/accounts/fo1415/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/fo1415/buildersgemsname.webp",
      "/accounts/fo1415/items.webp",
      "/accounts/fo1415/medals.webp",
      "/accounts/fo1415/scene.webp",
    ],
    heroskins: [
      "/accounts/fo1415/kingskin.webp",
      "/accounts/fo1415/queenskin.webp",
      "/accounts/fo1415/wardenskin.webp",
      "/accounts/fo1415/championskin.webp",
    ],
    price: 200,
  },
  {
    id: "266837",
    secretname: "strange",
    title: "well balance th 15",
    cover: "/accounts/strange/cover.webp",
    th: "155",
    heroes: {
      king: 68,
      queen: 83,
      warden: 59,
      champion: 30,
    },
    walls: {
      lvl13: 60,
      lvl14: 220,
      lvl15: 45,
    },
    monolith: 2,
    eagle: 6,
    scatter: [4, 4],
    inferno: [9, 9, 9],
    spelltower: [3, 3],
    xbow: [10, 10, 9, 9],
    airdefense: [13, 12, 12, 12],
    wizzard: [14, 14, 14, 14, 14],
    tesla: [13, 13, 13, 13, 13],
    archer: [20, 20, 20, 20, 20, 20, 20, 20],
    cannon: [20, 20, 20, 20, 20, 20, 20],
    sweeper: [7, 7],
    bombtower: [9, 9],
    mortar: [14, 14, 14, 14],
    builderhut: [4, 4, 4, 4, 4, 6],
    pethouse: 7,
    workshop: 6,
    spellfactory: 7,
    darkspell: 5,
    barraks: 16,
    darkbarraks: 9,
    armycamps: [12, 12, 12, 12],
    mainimgs: [
      "/accounts/strange/cover.webp",
      "/accounts/strange/bb1.webp",
      "/accounts/strange/bb2.webp",
      "/accounts/strange/mainstatus.webp",
      "/accounts/strange/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/strange/buildersgemsname.webp",
      "/accounts/strange/items.webp",
      "/accounts/strange/medals.webp",
      "/accounts/strange/scene.webp",
    ],
    heroskins: [
      "/accounts/strange/kingskin.webp",
      "/accounts/strange/queenskin.webp",
      "/accounts/strange/wardenskin.webp",
      "/accounts/strange/championskin.webp",
    ],
    price: 185,
  },
  {
    id: "978040",
    secretname: "antman",
    title: "well balance th 15",
    cover: "/accounts/antman/cover.webp",
    th: "155",
    heroes: {
      king: 75,
      queen: 82,
      warden: 58,
      champion: 26,
    },
    walls: {
      lvl15: 325,
    },
    monolith: 2,
    eagle: 6,
    scatter: [4, 3],
    inferno: [9, 8, 8],
    spelltower: [1, 1],
    xbow: [10, 10, 9, 9],
    airdefense: [13, 13, 12, 12],
    wizzard: [14, 14, 14, 14, 14],
    tesla: [13, 10, 10, 10, 10],
    archer: [20, 20, 20, 20, 19, 19, 19, 19],
    cannon: [20, 19, 19, 19, 19, 19, 18],
    sweeper: [7, 7],
    bombtower: [7, 7],
    mortar: [13, 12, 12, 12],
    builderhut: [3, 3, 2, 2, 2, 6],
    pethouse: 8,
    workshop: 7,
    spellfactory: 7,
    darkspell: 5,
    barraks: 16,
    darkbarraks: 10,
    armycamps: [12, 12, 12, 12],
    mainimgs: [
      "/accounts/antman/cover.webp",
      "/accounts/antman/bb1.webp",
      "/accounts/antman/bb2.webp",
      "/accounts/antman/mainstatus.webp",
      "/accounts/antman/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/antman/buildersgemsname.webp",
      "/accounts/antman/items.webp",
      "/accounts/antman/medals.webp",
      "/accounts/antman/scene.webp",
    ],
    heroskins: [
      "/accounts/antman/kingskin.webp",
      "/accounts/antman/queenskin.webp",
      "/accounts/antman/wardenskin.webp",
      "/accounts/antman/championskin.webp",
    ],
    price: 185,
  },
  {
    id: "553353",
    secretname: "ironman",
    title: "well balance th 15",
    cover: "/accounts/ironman/cover.webp",
    th: "155",
    heroes: {
      king: 80,
      queen: 84,
      warden: 60,
      champion: 30,
    },
    walls: {
      lvl12: 91,
      lvl13: 233,
      lvl14: 1,
    },
    monolith: 2,
    eagle: 6,
    scatter: [3, 3],
    inferno: [9, 9, 9],
    spelltower: [3, 3],
    xbow: [10, 9, 9, 9],
    airdefense: [12, 12, 12, 12],
    wizzard: [14, 14, 14, 14, 14],
    tesla: [13, 13, 13, 13, 13],
    archer: [20, 20, 20, 20, 20, 20, 20, 20],
    cannon: [20, 20, 20, 20, 20, 20, 20],
    sweeper: [7, 7],
    bombtower: [9, 9],
    mortar: [14, 14, 14, 14],
    builderhut: [4, 4, 4, 4, 4, 6],
    pethouse: 8,
    workshop: 7,
    spellfactory: 7,
    darkspell: 5,
    barraks: 16,
    darkbarraks: 9,
    armycamps: [12, 12, 12, 12],
    mainimgs: [
      "/accounts/ironman/cover.webp",
      "/accounts/ironman/bb1.webp",
      "/accounts/ironman/bb2.webp",
      "/accounts/ironman/mainstatus.webp",
      "/accounts/ironman/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/ironman/buildersgemsname.webp",
      "/accounts/ironman/items.webp",
      "/accounts/ironman/medals.webp",
      "/accounts/ironman/scene.webp",
    ],
    heroskins: [
      "/accounts/ironman/kingskin.webp",
      "/accounts/ironman/queenskin.webp",
      "/accounts/ironman/wardenskin.webp",
      "/accounts/ironman/championskin.webp",
    ],
    price: 190,
  },
  {
    id: "37423",
    secretname: "fo1315",
    title: "lower th 15",
    cover: "/accounts/fo1315/cover.webp",
    th: "155",
    heroes: {
      king: 55,
      queen: 73,
      warden: 54,
      champion: 20,
    },
    walls: {
      lvl12: 207,
      lvl13: 118,
    },
    monolith: 2,
    eagle: 6,
    scatter: [3, 3],
    inferno: [8, 7, 7],
    spelltower: [3, 2],
    xbow: [8, 8, 8, 8],
    airdefense: [12, 12, 12, 11],
    wizzard: [11, 11, 11, 11, 11],
    tesla: [11, 10, 10, 10, 10],
    archer: [19, 19, 19, 19, 19, 19, 19, 19],
    cannon: [19, 19, 19, 19, 19, 18, 18],
    sweeper: [7, 7],
    bombtower: [7, 7],
    mortar: [12, 12, 11, 11],
    builderhut: [1, 1, 1, 1, 1],
    pethouse: 6,
    workshop: 5,
    spellfactory: 7,
    darkspell: 5,
    barraks: 15,
    darkbarraks: 9,
    armycamps: [12, 12, 12, 12],
    mainimgs: [
      "/accounts/fo1315/cover.webp",
      "/accounts/fo1315/bb1.webp",
      "/accounts/fo1315/bb2.webp",
      "/accounts/fo1315/mainstatus.webp",
      "/accounts/fo1315/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/fo1315/buildersgemsname.webp",
      "/accounts/fo1315/items.webp",
      "/accounts/fo1315/medals.webp",
      "/accounts/fo1315/scene.webp",
    ],
    heroskins: [
      "/accounts/fo1315/kingskin.webp",
      "/accounts/fo1315/queenskin.webp",
      "/accounts/fo1315/wardenskin.webp",
      "/accounts/fo1315/championskin.webp",
    ],
    price: 130,
  },
  {
    id: "411980",
    secretname: "wolf",
    title: "rushed th 15",
    cover: "/accounts/wolf/cover.webp",
    th: "155",
    heroes: {
      king: 66,
      queen: 71,
      warden: 50,
      champion: 10,
    },
    walls: {
      lvl11: 19,
      lvl12: 5,
      lvl13: 291,
      lvl14: 10,
    },
    monolith: 2,
    eagle: 6,
    scatter: [3, 3],
    inferno: [8, 7, 7],
    spelltower: [3, 1],
    xbow: [8, 6, 6, 6],
    airdefense: [11, 11, 11, 11],
    wizzard: [12, 11, 11, 11, 11],
    tesla: [10, 10, 10, 10, 10],
    archer: [19, 19, 19, 18, 18, 18, 18, 18],
    cannon: [17, 17, 17, 17, 17, 17, 17],
    sweeper: [7, 7],
    bombtower: [7, 7],
    mortar: [12, 12, 12, 12],
    builderhut: [1, 1, 1, 1, 1],
    pethouse: 8,
    workshop: 4,
    spellfactory: 7,
    darkspell: 5,
    barraks: 15,
    darkbarraks: 9,
    armycamps: [12, 12, 12, 12],
    mainimgs: [
      "/accounts/wolf/cover.webp",
      "/accounts/wolf/bb1.webp",
      "/accounts/wolf/bb2.webp",
      "/accounts/wolf/mainstatus.webp",
      "/accounts/wolf/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/wolf/buildersgemsname.webp",
      "/accounts/wolf/items.webp",
      "/accounts/wolf/medals.webp",
      "/accounts/wolf/scene.webp",
    ],
    heroskins: [
      "/accounts/wolf/kingskin.webp",
      "/accounts/wolf/queenskin.webp",
      "/accounts/wolf/wardenskin.webp",
      "/accounts/wolf/championskin.webp",
    ],
    price: 125,
  },
  {
    id: "376818",
    secretname: "cipote",
    title: "rushed th 15",
    cover: "/accounts/cipote/cover.webp",
    th: "155",
    heroes: {
      king: 56,
      queen: 72,
      warden: 49,
      champion: 16,
    },
    walls: {
      lvl10: 24,
      lvl11: 1,
      lvl12: 232,
      lvl13: 68,
    },
    monolith: 2,
    eagle: 6,
    scatter: [4, 3],
    inferno: [9, 7, 7],
    spelltower: [3, 3],
    xbow: [8, 8, 8, 8],
    airdefense: [11, 11, 11, 11],
    wizzard: [13, 12, 11, 11, 11],
    tesla: [10, 10, 10, 10, 10],
    archer: [19, 19, 19, 19, 18, 18, 18, 18],
    cannon: [18, 18, 18, 18, 17, 17, 17],
    sweeper: [7, 7],
    bombtower: [7, 7],
    mortar: [13, 12, 12, 12],
    builderhut: [1, 1, 1, 1, 1],
    pethouse: 8,
    workshop: 5,
    spellfactory: 7,
    darkspell: 5,
    barraks: 15,
    darkbarraks: 10,
    armycamps: [12, 12, 12, 12],
    mainimgs: [
      "/accounts/cipote/cover.webp",
      "/accounts/cipote/bb1.webp",
      "/accounts/cipote/bb2.webp",
      "/accounts/cipote/mainstatus.webp",
      "/accounts/cipote/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/cipote/buildersgemsname.webp",
      "/accounts/cipote/items.webp",
      "/accounts/cipote/medals.webp",
      "/accounts/cipote/scene.webp",
    ],
    heroskins: [
      "/accounts/cipote/kingskin.webp",
      "/accounts/cipote/queenskin.webp",
      "/accounts/cipote/wardenskin.webp",
      "/accounts/cipote/championskin.webp",
    ],
    price: 125,
  },
  {
    id: "538810",
    secretname: "loco",
    title: "rushed th 15",
    cover: "/accounts/loco/cover.webp",
    th: "155",
    heroes: {
      king: 66,
      queen: 71,
      warden: 49,
      champion: 10,
    },
    walls: {
      lvl11: 81,
      lvl12: 243,
      lvl13: 1,
    },
    monolith: 2,
    eagle: 6,
    scatter: [3, 3],
    inferno: [8, 7, 7],
    spelltower: [1, 1],
    xbow: [6, 6, 6, 6],
    airdefense: [11, 11, 10, 10],
    wizzard: [11, 11, 11, 11, 11],
    tesla: [10, 10, 10, 10, 10],
    archer: [19, 18, 18, 18, 17, 17, 17, 17],
    cannon: [16, 15, 15, 15, 15, 15, 15],
    sweeper: [7, 7],
    bombtower: [5, 5],
    mortar: [10, 10, 10, 10],
    builderhut: [1, 1, 1, 1, 1],
    pethouse: 4,
    workshop: 4,
    spellfactory: 7,
    darkspell: 5,
    barraks: 15,
    darkbarraks: 9,
    armycamps: [12, 12, 12, 12],
    mainimgs: [
      "/accounts/loco/cover.webp",
      "/accounts/loco/bb1.webp",
      "/accounts/loco/bb2.webp",
      "/accounts/loco/mainstatus.webp",
      "/accounts/loco/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/loco/buildersgemsname.webp",
      "/accounts/loco/items.webp",
      "/accounts/loco/medals.webp",
      "/accounts/loco/scene.webp",
    ],
    heroskins: [
      "/accounts/loco/kingskin.webp",
      "/accounts/loco/queenskin.webp",
      "/accounts/loco/wardenskin.webp",
      "/accounts/loco/championskin.webp",
    ],
    price: 110,
  },
  {
    id: "45010",
    secretname: "penetrator",
    title: "rushed th 15",
    cover: "/accounts/penetrator/cover.webp",
    th: "155",
    heroes: {
      king: 66,
      queen: 71,
      warden: 49,
      champion: 11,
    },
    walls: {
      lvl10: 3,
      lvl11: 22,
      lvl12: 64,
      lvl13: 236,
    },
    monolith: 2,
    eagle: 6,
    scatter: [3, 3],
    inferno: [7, 7, 7],
    spelltower: [3, 1],
    xbow: [6, 6, 6, 6],
    airdefense: [11, 11, 10, 10],
    wizzard: [11, 11, 11, 11, 11],
    tesla: [10, 10, 10, 10, 9],
    archer: [19, 19, 19, 19, 18, 18, 18, 18],
    cannon: [16, 16, 15, 15, 15, 15, 14],
    sweeper: [7, 6],
    bombtower: [4, 4],
    mortar: [12, 7, 7, 7],
    builderhut: [1, 1, 1, 1, 1, 6],
    pethouse: 6,
    workshop: 5,
    spellfactory: 6,
    darkspell: 5,
    barraks: 15,
    darkbarraks: 9,
    armycamps: [12, 12, 12, 12],
    mainimgs: [
      "/accounts/penetrator/cover.webp",
      "/accounts/penetrator/bb1.webp",
      "/accounts/penetrator/bb2.webp",
      "/accounts/penetrator/mainstatus.webp",
      "/accounts/penetrator/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/penetrator/buildersgemsname.webp",
      "/accounts/penetrator/items.webp",
      "/accounts/penetrator/medals.webp",
      "/accounts/penetrator/scene.webp",
    ],
    heroskins: [
      "/accounts/penetrator/kingskin.webp",
      "/accounts/penetrator/queenskin.webp",
      "/accounts/penetrator/wardenskin.webp",
      "/accounts/penetrator/championskin.webp",
    ],
    price: 110,
  },
  {
    id: "932366",
    secretname: "toyo",
    title: "maxed th14 walls left",
    cover: "/accounts/toyo/cover.webp",
    th: "145",
    heroes: {
      king: 80,
      queen: 80,
      warden: 55,
      champion: 30,
    },
    walls: {
      lvl14: 318,
      lvl15: 7,
    },
    eagle: 5,
    scatter: [3, 3],
    inferno: [8, 8, 8],
    xbow: [9, 9, 9, 9],
    airdefense: [12, 12, 12, 12],
    wizzard: [14, 14, 14, 14, 14],
    tesla: [13, 13, 13, 13, 13],
    archer: [20, 20, 20, 20, 20, 20, 20, 20],
    cannon: [20, 20, 20, 20, 20, 20, 20],
    sweeper: [7, 7],
    bombtower: [9, 9],
    mortar: [14, 14, 14, 14],
    builderhut: [4, 4, 4, 4, 4, 6],
    pethouse: 4,
    workshop: 7,
    spellfactory: 7,
    darkspell: 5,
    barraks: 16,
    darkbarraks: 10,
    armycamps: [11, 11, 11, 11],
    mainimgs: [
      "/accounts/toyo/cover.webp",
      "/accounts/toyo/bb1.webp",
      "/accounts/toyo/bb2.webp",
      "/accounts/toyo/mainstatus.webp",
      "/accounts/toyo/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/toyo/buildersgemsname.webp",
      "/accounts/toyo/items.webp",
      "/accounts/toyo/medals.webp",
      "/accounts/toyo/scene.webp",
    ],
    heroskins: [
      "/accounts/toyo/kingskin.webp",
      "/accounts/toyo/queenskin.webp",
      "/accounts/toyo/wardenskin.webp",
      "/accounts/toyo/championskin.webp",
    ],
    price: 180,
  },
  {
    id: "882479",
    secretname: "panther",
    title: "maxed th14 walls left",
    cover: "/accounts/panther/cover.webp",
    th: "145",
    heroes: {
      king: 80,
      queen: 80,
      warden: 55,
      champion: 30,
    },
    walls: {
      lvl13: 34,
      lvl14: 288,
      lvl15: 3,
    },
    eagle: 5,
    scatter: [3, 3],
    inferno: [8, 8, 8],
    xbow: [9, 9, 9, 9],
    airdefense: [12, 12, 12, 12],
    wizzard: [14, 14, 14, 14, 14],
    tesla: [13, 13, 13, 13, 13],
    archer: [20, 20, 20, 20, 20, 20, 20, 20],
    cannon: [20, 20, 20, 20, 20, 20, 20],
    sweeper: [7, 7],
    bombtower: [9, 9],
    mortar: [14, 14, 14, 14],
    builderhut: [4, 4, 4, 4, 4, 6],
    pethouse: 4,
    workshop: 7,
    spellfactory: 7,
    darkspell: 5,
    barraks: 16,
    darkbarraks: 10,
    armycamps: [11, 11, 11, 11],
    mainimgs: [
      "/accounts/panther/cover.webp",
      "/accounts/panther/bb1.webp",
      "/accounts/panther/bb2.webp",
      "/accounts/panther/mainstatus.webp",
      "/accounts/panther/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/panther/buildersgemsname.webp",
      "/accounts/panther/items.webp",
      "/accounts/panther/medals.webp",
      "/accounts/panther/scene.webp",
    ],
    heroskins: [
      "/accounts/panther/kingskin.webp",
      "/accounts/panther/queenskin.webp",
      "/accounts/panther/wardenskin.webp",
      "/accounts/panther/championskin.webp",
    ],
    price: 180,
  },
  {
    id: "189593",
    secretname: "hulk",
    title: "maxed th14 walls & 2 laboratory upgrades left",
    cover: "/accounts/hulk/cover.webp",
    th: "145",
    heroes: {
      king: 80,
      queen: 80,
      warden: 55,
      champion: 30,
    },
    walls: {
      lvl13: 269,
      lvl14: 56,
    },
    eagle: 5,
    scatter: [3, 3],
    inferno: [8, 8, 8],
    xbow: [9, 9, 9, 9],
    airdefense: [12, 12, 12, 12],
    wizzard: [14, 14, 14, 14, 14],
    tesla: [13, 13, 13, 13, 13],
    archer: [20, 20, 20, 20, 20, 20, 20, 20],
    cannon: [20, 20, 20, 20, 20, 20, 20],
    sweeper: [7, 7],
    bombtower: [9, 9],
    mortar: [14, 14, 14, 14],
    builderhut: [4, 4, 4, 4, 4, 6],
    pethouse: 4,
    workshop: 7,
    spellfactory: 7,
    darkspell: 5,
    barraks: 16,
    darkbarraks: 10,
    armycamps: [11, 11, 11, 11],
    mainimgs: [
      "/accounts/hulk/cover.webp",
      "/accounts/hulk/bb1.webp",
      "/accounts/hulk/bb2.webp",
      "/accounts/hulk/mainstatus.webp",
      "/accounts/hulk/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/hulk/buildersgemsname.webp",
      "/accounts/hulk/items.webp",
      "/accounts/hulk/medals.webp",
      "/accounts/hulk/scene.webp",
    ],
    heroskins: [
      "/accounts/hulk/kingskin.webp",
      "/accounts/hulk/queenskin.webp",
      "/accounts/hulk/wardenskin.webp",
      "/accounts/hulk/championskin.webp",
    ],
    price: 175,
  },
  {
    id: "5404",
    secretname: "pichulin",
    title: "rushed th 14",
    cover: "/accounts/pichulin/cover.webp",
    th: "145",
    heroes: {
      king: 66,
      queen: 69,
      warden: 48,
      champion: 13,
    },
    walls: {
      lvl1: 3,
      lvl5: 22,
      lvl12: 198,
      lvl13: 102,
    },

    eagle: 4,
    scatter: [3, 3],
    inferno: [7, 7, 7],
    xbow: [8, 8, 8, 6],
    airdefense: [11, 11, 11, 11],
    wizzard: [11, 11, 11, 11, 11],
    tesla: [10, 10, 10, 10, 10],
    archer: [19, 19, 19, 19, 19, 18, 18, 18],
    cannon: [18, 18, 17, 17, 17, 17, 17],
    sweeper: [7, 7],
    bombtower: [7, 7],
    mortar: [12, 12, 12, 12],
    builderhut: [1, 1, 1, 1, 1],

    workshop: 5,
    spellfactory: 7,
    darkspell: 5,
    barraks: 15,
    darkbarraks: 9,
    pethouse: 4,
    armycamps: [11, 11, 11, 11],
    mainimgs: [
      "/accounts/pichulin/cover.webp",
      "/accounts/pichulin/bb1.webp",
      "/accounts/pichulin/bb2.webp",
      "/accounts/pichulin/mainstatus.webp",
      "/accounts/pichulin/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/pichulin/buildersgemsname.webp",
      "/accounts/pichulin/items.webp",
      "/accounts/pichulin/medals.webp",
      "/accounts/pichulin/scene.webp",
    ],
    heroskins: [
      "/accounts/pichulin/kingskin.webp",
      "/accounts/pichulin/queenskin.webp",
      "/accounts/pichulin/wardenskin.webp",
      "/accounts/pichulin/championskin.webp",
    ],
    price: 100,
  },
  {
    id: "372575",
    secretname: "fo13",
    title: "maxed th 13",
    cover: "/accounts/fo13/cover.webp",
    th: "135",
    heroes: {
      king: 75,
      queen: 75,
      warden: 50,
      champion: 25,
    },
    walls: {
      lvl14: 300,
    },

    eagle: 4,
    scatter: [2, 2],
    inferno: [7, 7, 7],
    xbow: [8, 8, 8, 8],
    airdefense: [11, 11, 11, 11],
    wizzard: [12, 12, 12, 12, 12],
    tesla: [12, 12, 12, 12, 12],
    archer: [19, 19, 19, 19, 19, 19, 19, 19],
    cannon: [19, 19, 19, 19, 19, 19, 19],
    sweeper: [7, 7],
    bombtower: [8, 8],
    mortar: [12, 12, 12, 12],
    builderhut: [1, 1, 1, 1, 1, 6],

    workshop: 5,
    spellfactory: 7,
    darkspell: 5,
    barraks: 15,
    darkbarraks: 10,
    armycamps: [11, 11, 11, 11],
    mainimgs: [
      "/accounts/fo13/cover.webp",
      "/accounts/fo13/bb1.webp",
      "/accounts/fo13/bb2.webp",
      "/accounts/fo13/mainstatus.webp",
      "/accounts/fo13/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/fo13/buildersgemsname.webp",
      "/accounts/fo13/items.webp",
      "/accounts/fo13/medals.webp",
      "/accounts/fo13/scene.webp",
    ],
    heroskins: [
      "/accounts/fo13/kingskin.webp",
      "/accounts/fo13/queenskin.webp",
      "/accounts/fo13/wardenskin.webp",
      "/accounts/fo13/championskin.webp",
    ],
    price: 140,
  },
  {
    id: "859895",
    secretname: "barney",
    title: "85%+ th 13",
    cover: "/accounts/barney/cover.webp",
    th: "135",
    heroes: {
      king: 67,
      queen: 71,
      warden: 50,
      champion: 15,
    },
    walls: {
      lvl13: 269,
      lvl14: 31,
    },

    eagle: 4,
    scatter: [2, 2],
    inferno: [7, 7, 7],
    xbow: [8, 8, 8, 8],
    airdefense: [11, 11, 11, 11],
    wizzard: [12, 11, 11, 11, 11],
    tesla: [10, 10, 10, 10, 10],
    archer: [19, 19, 19, 19, 19, 19, 19, 19],
    cannon: [19, 19, 19, 19, 18, 18, 18],
    sweeper: [7, 7],
    bombtower: [7, 7],
    mortar: [12, 12, 12, 12],
    builderhut: [1, 1, 1, 1, 1],

    workshop: 4,
    spellfactory: 7,
    darkspell: 5,
    barraks: 15,
    darkbarraks: 9,
    armycamps: [11, 11, 11, 11],
    mainimgs: [
      "/accounts/barney/cover.webp",
      "/accounts/barney/bb1.webp",
      "/accounts/barney/bb2.webp",
      "/accounts/barney/mainstatus.webp",
      "/accounts/barney/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/barney/buildersgemsname.webp",
      "/accounts/barney/items.webp",
      "/accounts/barney/medals.webp",
      "/accounts/barney/scene.webp",
    ],
    heroskins: [
      "/accounts/barney/kingskin.webp",
      "/accounts/barney/queenskin.webp",
      "/accounts/barney/wardenskin.webp",
      "/accounts/barney/championskin.webp",
    ],
    price: 120,
  },
  {
    id: "831059",
    secretname: "kiko",
    title: "80%+ th 13",
    cover: "/accounts/kiko/cover.webp",
    th: "135",
    heroes: {
      king: 66,
      queen: 72,
      warden: 50,
      champion: 13,
    },
    walls: {
      lvl13: 269,
      lvl14: 31,
    },

    eagle: 4,
    scatter: [2, 2],
    inferno: [7, 7, 7],
    xbow: [8, 8, 8, 8],
    airdefense: [11, 11, 11, 11],
    wizzard: [13, 11, 11, 11, 11],
    tesla: [10, 10, 10, 10, 10],
    archer: [19, 19, 19, 19, 19, 18, 18, 18],
    cannon: [18, 17, 16, 16, 16, 16, 16],
    sweeper: [7, 7],
    bombtower: [7, 7],
    mortar: [10, 10, 10, 10],
    builderhut: [1, 1, 1, 1, 1],

    workshop: 5,
    spellfactory: 7,
    darkspell: 5,
    barraks: 15,
    darkbarraks: 10,
    armycamps: [11, 11, 11, 11],
    mainimgs: [
      "/accounts/kiko/cover.webp",
      "/accounts/kiko/bb1.webp",
      "/accounts/kiko/bb2.webp",
      "/accounts/kiko/mainstatus.webp",
      "/accounts/kiko/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/kiko/buildersgemsname.webp",
      "/accounts/kiko/items.webp",
      "/accounts/kiko/medals.webp",
      "/accounts/kiko/scene.webp",
    ],
    heroskins: [
      "/accounts/kiko/kingskin.webp",
      "/accounts/kiko/queenskin.webp",
      "/accounts/kiko/wardenskin.webp",
      "/accounts/kiko/championskin.webp",
    ],
    price: 115,
  },
  {
    id: "507783",
    secretname: "gonso",
    title: "90%+ th 13",
    cover: "/accounts/gonso/cover.webp",
    th: "135",
    heroes: {
      king: 66,
      queen: 72,
      warden: 50,
      champion: 16,
    },
    walls: {
      lvl12: 58,
      lvl13: 241,
      lvl14: 1,
    },

    eagle: 4,
    scatter: [2, 2],
    inferno: [7, 7, 7],
    xbow: [8, 8, 8, 8],
    airdefense: [11, 11, 11, 11],
    wizzard: [13, 11, 11, 11, 11],
    tesla: [11, 10, 10, 10, 10],
    archer: [19, 19, 19, 19, 19, 19, 19, 19],
    cannon: [19, 18, 18, 18, 18, 18, 18],
    sweeper: [7, 7],
    bombtower: [7, 7],
    mortar: [12, 12, 12, 12],
    builderhut: [1, 1, 1, 1, 1, 6],

    workshop: 5,
    spellfactory: 7,
    darkspell: 5,
    barraks: 15,
    darkbarraks: 9,
    armycamps: [11, 11, 11, 11],
    mainimgs: [
      "/accounts/gonso/cover.webp",
      "/accounts/gonso/bb1.webp",
      "/accounts/gonso/bb2.webp",
      "/accounts/gonso/mainstatus.webp",
      "/accounts/gonso/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/gonso/buildersgemsname.webp",
      "/accounts/gonso/items.webp",
      "/accounts/gonso/medals.webp",
      "/accounts/gonso/scene.webp",
    ],
    heroskins: [
      "/accounts/gonso/kingskin.webp",
      "/accounts/gonso/queenskin.webp",
      "/accounts/gonso/wardenskin.webp",
      "/accounts/gonso/championskin.webp",
    ],
    price: 115,
  },
  {
    id: "422189",
    secretname: "fo12",
    title: "rushed th13",
    cover: "/accounts/fo1213/cover.webp",
    th: "135",
    heroes: {
      king: 52,
      queen: 61,
      warden: 29,
      champion: 1,
    },
    walls: {
      lvl12: 213,
      lvl13: 87,
    },
    scatter: [2, 1],
    eagle: 3,
    inferno: [6, 6, 6],
    xbow: [6, 6, 6, 6],
    airdefense: [10, 10, 10, 10],
    wizzard: [10, 10, 10, 10, 10],
    tesla: [10, 10, 9, 9, 6],
    archer: [18, 18, 17, 17, 16, 16, 16, 15],
    cannon: [16, 16, 15, 15, 15, 15, 15],
    sweeper: [7, 7],
    bombtower: [6, 6],
    mortar: [11, 10, 10, 10],
    builderhut: [1, 1, 1, 1, 1],

    spellfactory: 6,
    darkspell: 5,
    barraks: 14,
    darkbarraks: 9,
    armycamps: [10, 10, 10, 10],
    mainimgs: [
      "/accounts/fo1213/cover.webp",
      "/accounts/fo1213/bb1.webp",
      "/accounts/fo1213/bb2.webp",
      "/accounts/fo1213/mainstatus.webp",
      "/accounts/fo1213/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/fo1213/buildersgemsname.webp",
      "/accounts/fo1213/items.webp",
      "/accounts/fo1213/medals.webp",
      "/accounts/fo1213/scene.webp",
    ],
    heroskins: [
      "/accounts/fo1213/kingskin.webp",
      "/accounts/fo1213/queenskin.webp",
      "/accounts/fo1213/wardenskin.webp",
    ],
    price: 75,
  },
  {
    id: "334789",
    secretname: "fo12",
    title: "maxed th12",
    cover: "/accounts/fo12/cover.webp",
    th: "125",
    heroes: {
      king: 65,
      queen: 65,
      warden: 40,
    },
    walls: {
      lvl13: 300,
    },
    eagle: 3,
    inferno: [6, 6, 6],
    xbow: [6, 6, 6, 6],
    airdefense: [10, 10, 10, 10],
    wizzard: [11, 11, 11, 11, 11],
    tesla: [10, 10, 10, 10, 10],
    archer: [17, 17, 17, 17, 17, 17, 17, 17],
    cannon: [17, 17, 17, 17, 17, 17, 17],
    sweeper: [7, 7],
    bombtower: [7, 7],
    mortar: [12, 12, 12, 12],
    builderhut: [1, 1, 1, 1, 1],

    spellfactory: 6,
    darkspell: 5,
    barraks: 14,
    darkbarraks: 9,
    armycamps: [10, 10, 10, 10],
    mainimgs: [
      "/accounts/fo12/cover.webp",
      "/accounts/fo12/bb1.webp",
      "/accounts/fo12/bb2.webp",
      "/accounts/fo12/mainstatus.webp",
      "/accounts/fo12/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/fo12/buildersgemsname.webp",
      "/accounts/fo12/items.webp",
      "/accounts/fo12/medals.webp",
      "/accounts/fo12/scene.webp",
    ],
    heroskins: [
      "/accounts/fo12/kingskin.webp",
      "/accounts/fo12/queenskin.webp",
      "/accounts/fo12/wardenskin.webp",
    ],
    price: 100,
  },
  {
    id: "904712",
    secretname: "ak47",
    title: "non balance th12 scenery",
    cover: "/accounts/ak47/cover.webp",
    th: "125",
    heroes: {
      king: 26,
      queen: 41,
      warden: 17,
    },
    walls: {
      lvl10: 260,
      lvl11: 32,
      lvl12: 8,
    },
    eagle: 3,
    inferno: [6, 5, 1],
    xbow: [6, 5, 5, 5],
    airdefense: [10, 9, 9, 9],
    wizzard: [8, 8, 8, 7, 6],
    tesla: [9, 8, 8, 8, 4],
    archer: [15, 15, 13, 13, 13, 12, 12, 12],
    cannon: [15, 14, 13, 13, 12, 12, 12],
    sweeper: [5, 5],
    bombtower: [5, 3],
    mortar: [8, 7, 7, 7],
    builderhut: [1, 1, 1, 1, 1],

    spellfactory: 6,
    darkspell: 5,
    barraks: 14,
    darkbarraks: 8,
    armycamps: [9, 9, 9, 9],
    mainimgs: [
      "/accounts/ak47/cover.webp",
      "/accounts/ak47/bb1.webp",
      "/accounts/ak47/bb2.webp",
      "/accounts/ak47/mainstatus.webp",
      "/accounts/ak47/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/ak47/buildersgemsname.webp",
      "/accounts/ak47/items.webp",
      "/accounts/ak47/medals.webp",
      "/accounts/ak47/scene.webp",
    ],
    heroskins: [
      "/accounts/ak47/kingskin.webp",
      "/accounts/ak47/queenskin.webp",
      "/accounts/ak47/wardenskin.webp",
    ],
    price: 70,
  },
  {
    id: "817724",
    secretname: "hieu",
    title: "98% maxed th 11",
    cover: "/accounts/hieu/cover.webp",
    th: "11",
    heroes: {
      king: 50,
      queen: 50,
      warden: 20,
    },
    walls: {
      lvl12: 300,
    },
    eagle: 2,
    inferno: [5, 5],
    xbow: [5, 5, 5, 5],
    airdefense: [9, 9, 9, 9],
    wizzard: [10, 10, 10, 10, 10],
    tesla: [9, 9, 9, 9],
    archer: [15, 15, 15, 15, 15, 15, 15, 15],
    cannon: [15, 15, 14, 14, 14, 14, 14],
    sweeper: [7, 7],
    bombtower: [6, 6],
    mortar: [10, 10, 10, 9],
    builderhut: [1, 1, 1, 1, 1],

    spellfactory: 6,
    darkspell: 5,
    barraks: 13,
    darkbarraks: 8,
    armycamps: [9, 9, 9, 9],
    mainimgs: [
      "/accounts/hieu/cover.webp",
      "/accounts/hieu/bb1.webp",
      "/accounts/hieu/bb2.webp",
      "/accounts/hieu/mainstatus.webp",
      "/accounts/hieu/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/hieu/buildersgemsname.webp",
      "/accounts/hieu/items.webp",
      "/accounts/hieu/medals.webp",
      "/accounts/hieu/scene.webp",
    ],
    heroskins: [
      "/accounts/hieu/kingskin.webp",
      "/accounts/hieu/queenskin.webp",
      "/accounts/hieu/wardenskin.webp",
    ],
    price: 65,
  },
  {
    id: "838043",
    secretname: "fo11",
    title: "anniversary scenery maxed th 11",
    cover: "/accounts/fo11/cover.webp",
    th: "11",
    heroes: {
      king: 50,
      queen: 50,
      warden: 20,
    },
    walls: {
      lvl12: 300,
    },
    eagle: 2,
    inferno: [5, 5],
    xbow: [5, 5, 5, 5],
    airdefense: [9, 9, 9, 9],
    wizzard: [10, 10, 10, 10, 10],
    tesla: [9, 9, 9, 9],
    archer: [15, 15, 15, 15, 15, 15, 15, 15],
    cannon: [15, 15, 14, 14, 14, 14, 14],
    sweeper: [7, 7],
    bombtower: [6, 6],
    mortar: [10, 10, 10, 9],
    builderhut: [1, 1, 1, 1, 1],

    spellfactory: 6,
    darkspell: 5,
    barraks: 13,
    darkbarraks: 8,
    armycamps: [9, 9, 9, 9],
    mainimgs: [
      "/accounts/fo11/cover.webp",
      "/accounts/fo11/bb1.webp",
      "/accounts/fo11/bb2.webp",
      "/accounts/fo11/mainstatus.webp",
      "/accounts/fo11/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/fo11/buildersgemsname.webp",
      "/accounts/fo11/items.webp",
      "/accounts/fo11/medals.webp",
      "/accounts/fo11/scene.webp",
    ],
    heroskins: [
      "/accounts/fo11/kingskin.webp",
      "/accounts/fo11/queenskin.webp",
      "/accounts/fo11/wardenskin.webp",
    ],
    price: 80,
  },
  {
    id: "799301",
    secretname: "ben",
    title: "maxed th 11 scenery skins",
    cover: "/accounts/ben/cover.webp",
    th: "11",
    heroes: {
      king: 50,
      queen: 50,
      warden: 20,
    },
    walls: {
      lvl12: 300,
    },
    eagle: 2,
    inferno: [5, 5],
    xbow: [5, 5, 5, 5],
    airdefense: [9, 9, 9, 9],
    wizzard: [10, 10, 10, 10, 10],
    tesla: [9, 9, 9, 9],
    archer: [15, 15, 15, 15, 15, 15, 15, 15],
    cannon: [15, 15, 14, 14, 14, 14, 14],
    sweeper: [7, 7],
    bombtower: [6, 6],
    mortar: [10, 10, 10, 9],
    builderhut: [1, 1, 1, 1, 1],

    spellfactory: 6,
    darkspell: 5,
    barraks: 13,
    darkbarraks: 8,
    armycamps: [9, 9, 9, 9],
    mainimgs: [
      "/accounts/ben/cover.webp",
      "/accounts/ben/bb1.webp",
      "/accounts/ben/bb2.webp",
      "/accounts/ben/mainstatus.webp",
      "/accounts/ben/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/ben/buildersgemsname.webp",
      "/accounts/ben/items.webp",
      "/accounts/ben/medals.webp",
      "/accounts/ben/scene.webp",
    ],
    heroskins: [
      "/accounts/ben/kingskin.webp",
      "/accounts/ben/queenskin.webp",
      "/accounts/ben/wardenskin.webp",
    ],
    price: 70,
  },
  {
    id: "598934",
    secretname: "qq",
    title: "maxed th 11 skins",
    cover: "/accounts/qq/cover.webp",
    th: "11",
    heroes: {
      king: 50,
      queen: 50,
      warden: 20,
    },
    walls: {
      lvl12: 300,
    },
    eagle: 2,
    inferno: [5, 5],
    xbow: [5, 5, 5, 5],
    airdefense: [9, 9, 9, 9],
    wizzard: [10, 10, 10, 10, 10],
    tesla: [9, 9, 9, 9],
    archer: [15, 15, 15, 15, 15, 15, 15, 15],
    cannon: [15, 15, 14, 14, 14, 14, 14],
    sweeper: [7, 7],
    bombtower: [6, 6],
    mortar: [10, 10, 10, 9],
    builderhut: [1, 1, 1, 1, 1],

    spellfactory: 6,
    darkspell: 5,
    barraks: 13,
    darkbarraks: 8,
    armycamps: [9, 9, 9, 9],
    mainimgs: [
      "/accounts/qq/cover.webp",
      "/accounts/qq/bb1.webp",
      "/accounts/qq/bb2.webp",
      "/accounts/qq/mainstatus.webp",
      "/accounts/qq/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/qq/buildersgemsname.webp",
      "/accounts/qq/items.webp",
      "/accounts/qq/medals.webp",
      "/accounts/qq/scene.webp",
    ],
    heroskins: [
      "/accounts/qq/kingskin.webp",
      "/accounts/qq/queenskin.webp",
      "/accounts/qq/wardenskin.webp",
    ],
    price: 65,
  },
  {
    id: "662646",
    secretname: "pirate",
    title: "maxed defenses th 10 2/scenery laboratory upgrades",
    cover: "/accounts/pirate/cover.webp",
    th: "10",
    heroes: {
      king: 40,
      queen: 40,
    },
    walls: {
      lvl11: 275,
    },
    inferno: [3, 3],
    xbow: [4, 4, 4],
    airdefense: [8, 8, 8, 8],
    wizzard: [9, 9, 9, 9],
    tesla: [8, 8, 8, 8],
    archer: [13, 13, 13, 13, 13, 13, 13],
    cannon: [13, 13, 13, 13, 13, 13],
    sweeper: [6, 6],
    bombtower: [4, 4],
    mortar: [8, 8, 8, 8],
    builderhut: [1, 1, 1, 1],
    spellfactory: 5,
    darkspell: 5,
    barraks: 12,
    darkbarraks: 7,
    armycamps: [8, 8, 8, 8],
    mainimgs: [
      "/accounts/pirate/cover.webp",
      "/accounts/pirate/bb1.webp",
      "/accounts/pirate/mainstatus.webp",
      "/accounts/pirate/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/pirate/buildersgemsname.webp",
      "/accounts/pirate/items.webp",
      "/accounts/pirate/medals.webp",
      "/accounts/pirate/scene.webp",
    ],
    heroskins: [
      "/accounts/pirate/kingskin.webp",
      "/accounts/pirate/queenskin.webp",
    ],
    price: 53,
  },
  {
    id: "284754",
    secretname: "fo10",
    title: "maxed th 10 items medals",
    cover: "/accounts/fo10/cover.webp",
    th: "10",
    heroes: {
      king: 40,
      queen: 40,
    },
    walls: {
      lvl11: 275,
    },
    inferno: [3, 3],
    xbow: [4, 4, 4],
    airdefense: [8, 8, 8, 8],
    wizzard: [9, 9, 9, 9],
    tesla: [8, 8, 8, 8],
    archer: [13, 13, 13, 13, 13, 13, 13],
    cannon: [13, 13, 13, 13, 13, 13],
    sweeper: [6, 6],
    bombtower: [4, 4],
    mortar: [8, 8, 8, 8],
    builderhut: [1, 1, 1, 1],
    spellfactory: 5,
    darkspell: 5,
    barraks: 12,
    darkbarraks: 7,
    armycamps: [8, 8, 8, 8],
    mainimgs: [
      "/accounts/fo10/cover.webp",
      "/accounts/fo10/bb1.webp",
      "/accounts/fo10/mainstatus.webp",
      "/accounts/fo10/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/fo10/buildersgemsname.webp",
      "/accounts/fo10/items.webp",
      "/accounts/fo10/medals.webp",
      "/accounts/fo10/scene.webp",
    ],
    heroskins: [
      "/accounts/fo10/kingskin.webp",
      "/accounts/fo10/queenskin.webp",
    ],
    price: 55,
  },
  {
    id: "610375",
    secretname: "gladiator",
    title: "maxed th 10",
    cover: "/accounts/gladiator/cover.webp",
    th: "10",
    heroes: {
      king: 40,
      queen: 40,
    },
    walls: {
      lvl11: 275,
    },
    inferno: [3, 3],
    xbow: [4, 4, 4],
    airdefense: [8, 8, 8, 8],
    wizzard: [9, 9, 9, 9],
    tesla: [8, 8, 8, 8],
    archer: [13, 13, 13, 13, 13, 13, 13],
    cannon: [13, 13, 13, 13, 13, 13],
    sweeper: [6, 6],
    bombtower: [4, 4],
    mortar: [8, 8, 8, 8],
    builderhut: [1, 1, 1, 1],
    spellfactory: 5,
    darkspell: 5,
    barraks: 12,
    darkbarraks: 7,
    armycamps: [8, 8, 8, 8],
    mainimgs: [
      "/accounts/gladiator/cover.webp",
      "/accounts/gladiator/bb1.webp",
      "/accounts/gladiator/bb2.webp",
      "/accounts/gladiator/mainstatus.webp",
      "/accounts/gladiator/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/gladiator/buildersgemsname.webp",
      "/accounts/gladiator/items.webp",
      "/accounts/gladiator/medals.webp",
      "/accounts/gladiator/scene.webp",
    ],
    heroskins: [
      "/accounts/gladiator/kingskin.webp",
      "/accounts/gladiator/queenskin.webp",
    ],
    price: 50,
  },
  {
    id: "812334",
    secretname: "ten",
    title: "maxed th 10 scenery",
    cover: "/accounts/ten/cover.webp",
    th: "10",
    heroes: {
      king: 40,
      queen: 40,
    },
    walls: {
      lvl11: 275,
    },
    inferno: [3, 3],
    xbow: [4, 4, 4],
    airdefense: [8, 8, 8, 8],
    wizzard: [9, 9, 9, 9],
    tesla: [8, 8, 8, 8],
    archer: [13, 13, 13, 13, 13, 13, 13],
    cannon: [13, 13, 13, 13, 13, 13],
    sweeper: [6, 6],
    bombtower: [4, 4],
    mortar: [8, 8, 8, 8],
    builderhut: [1, 1, 1, 1],
    spellfactory: 5,
    darkspell: 5,
    barraks: 12,
    darkbarraks: 7,
    armycamps: [8, 8, 8, 8],
    mainimgs: [
      "/accounts/ten/cover.webp",
      "/accounts/ten/bb1.webp",
      "/accounts/ten/bb2.webp",
      "/accounts/ten/mainstatus.webp",
      "/accounts/ten/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/ten/buildersgemsname.webp",
      "/accounts/ten/items.webp",
      "/accounts/ten/medals.webp",
      "/accounts/ten/scene.webp",
    ],
    heroskins: ["/accounts/ten/kingskin.webp", "/accounts/ten/queenskin.webp"],
    price: 50,
  },
  {
    id: "822660",
    secretname: "papi",
    title: "maxed th 10 scenery",
    cover: "/accounts/papi/cover.webp",
    th: "10",
    heroes: {
      king: 40,
      queen: 40,
    },
    walls: {
      lvl11: 275,
    },
    inferno: [3, 3],
    xbow: [4, 4, 4],
    airdefense: [8, 8, 8, 8],
    wizzard: [9, 9, 9, 9],
    tesla: [8, 8, 8, 8],
    archer: [13, 13, 13, 13, 13, 13, 13],
    cannon: [13, 13, 13, 13, 13, 13],
    sweeper: [6, 6],
    bombtower: [4, 4],
    mortar: [8, 8, 8, 8],
    builderhut: [1, 1, 1, 1],
    spellfactory: 5,
    darkspell: 5,
    barraks: 12,
    darkbarraks: 7,
    armycamps: [8, 8, 8, 8],
    mainimgs: [
      "/accounts/papi/cover.webp",
      "/accounts/papi/bb1.webp",
      "/accounts/papi/bb2.webp",
      "/accounts/papi/mainstatus.webp",
      "/accounts/papi/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/papi/buildersgemsname.webp",
      "/accounts/papi/items.webp",
      "/accounts/papi/medals.webp",
      "/accounts/papi/scene.webp",
    ],
    heroskins: [
      "/accounts/papi/kingskin.webp",
      "/accounts/papi/queenskin.webp",
    ],
    price: 50,
  },
  {
    id: "281892",
    secretname: "arab",
    title: "maxed th 9",
    cover: "/accounts/arab9/cover.webp",
    th: "9",
    heroes: {
      king: 30,
      queen: 30,
    },
    walls: {
      lvl10: 250,
    },
    xbow: [3, 3],
    airdefense: [7, 7, 7, 7],
    wizzard: [7, 7, 7, 7],
    tesla: [7, 7, 7, 7],
    archer: [11, 11, 11, 11, 11, 11],
    cannon: [11, 11, 11, 11, 11],
    sweeper: [5, 5],
    bombtower: [3],
    mortar: [7, 7, 7, 7],
    builderhut: [1, 1, 1, 1],
    spellfactory: 4,
    darkspell: 4,
    barraks: 11,
    darkbarraks: 6,
    armycamps: [7, 7, 7, 7],
    mainimgs: [
      "/accounts/arab9/cover.webp",
      "/accounts/arab9/bb1.webp",
      "/accounts/arab9/mainstatus.webp",
      "/accounts/arab9/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/arab9/buildersgemsname.webp",
      "/accounts/arab9/items.webp",
      "/accounts/arab9/medals.webp",
      "/accounts/arab9/scene.webp",
    ],
    heroskins: [
      "/accounts/arab9/kingskin.webp",
      "/accounts/arab9/queenskin.webp",
    ],
    price: 32,
  },
  {
    id: "364711",
    secretname: "nine",
    title: "maxed th 9",
    cover: "/accounts/nine/cover.webp",
    th: "9",
    heroes: {
      king: 30,
      queen: 30,
    },
    walls: {
      lvl10: 250,
    },
    xbow: [3, 3],
    airdefense: [7, 7, 7, 7],
    wizzard: [7, 7, 7, 7],
    tesla: [7, 7, 7, 7],
    archer: [11, 11, 11, 11, 11, 11],
    cannon: [11, 11, 11, 11, 11],
    sweeper: [5, 5],
    bombtower: [3],
    mortar: [7, 7, 7, 7],
    builderhut: [1, 1, 1, 1],
    spellfactory: 4,
    darkspell: 4,
    barraks: 11,
    darkbarraks: 6,
    armycamps: [7, 7, 7, 7],
    mainimgs: [
      "/accounts/nine/cover.webp",
      "/accounts/nine/bb1.webp",
      "/accounts/nine/bb2.webp",
      "/accounts/nine/mainstatus.webp",
      "/accounts/nine/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/nine/buildersgemsname.webp",
      "/accounts/nine/items.webp",
      "/accounts/nine/medals.webp",
      "/accounts/nine/scene.webp",
    ],
    heroskins: [
      "/accounts/nine/kingskin.webp",
      "/accounts/nine/queenskin.webp",
    ],
    price: 32,
  },
  {
    id: "974644",
    secretname: "nueve",
    title: "maxed th 9",
    cover: "/accounts/nueve/cover.webp",
    th: "9",
    heroes: {
      king: 30,
      queen: 30,
    },
    walls: {
      lvl10: 250,
    },
    xbow: [3, 3],
    airdefense: [7, 7, 7, 7],
    wizzard: [7, 7, 7, 7],
    tesla: [7, 7, 7, 7],
    archer: [11, 11, 11, 11, 11, 11],
    cannon: [11, 11, 11, 11, 11],
    sweeper: [5, 5],
    bombtower: [3],
    mortar: [7, 7, 7, 7],
    builderhut: [1, 1, 1, 1],
    spellfactory: 4,
    darkspell: 4,
    barraks: 11,
    darkbarraks: 6,
    armycamps: [7, 7, 7, 7],
    mainimgs: [
      "/accounts/nueve/cover.webp",
      "/accounts/nueve/bb1.webp",
      "/accounts/nueve/bb2.webp",
      "/accounts/nueve/mainstatus.webp",
      "/accounts/nueve/builderstatus.webp",
    ],
    itemsimgs: [
      "/accounts/nueve/buildersgemsname.webp",
      "/accounts/nueve/items.webp",
      "/accounts/nueve/medals.webp",
      "/accounts/nueve/scene.webp",
    ],
    heroskins: [
      "/accounts/nueve/kingskin.webp",
      "/accounts/nueve/queenskin.webp",
    ],
    price: 39,
  },
];
